[workspace]
members = [
    "fedimintd",
    "fedimint-cli",
    "roastr-common",
    "roastr-client",
    "roastr-server",
    "roastr-tests",
]
resolver = "2"

[workspace.metadata]
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Fedimint compiled with custom module set"
documentation = "https://github.com/fedimint/fedimint-custom-modules-example"
readme = "README.md"
homepage = "https://github.com/fedimint/fedimint-custom-modules-example"
repository = "https://github.com/fedimint/fedimint-custom-modules-example"
license-file = "LICENSE"
keywords = ["bitcoin", "lightning", "chaumian", "e-cash", "federated"]

[workspace.dependencies]
fedimintd = { git = "https://github.com/fedimint/fedimint", rev = "33f80b29ca0640ed83d66d6823aa1e12f09da126" }
fedimint-cli = { git = "https://github.com/fedimint/fedimint", rev = "33f80b29ca0640ed83d66d6823aa1e12f09da126" }
fedimint-core = { git = "https://github.com/fedimint/fedimint", rev = "33f80b29ca0640ed83d66d6823aa1e12f09da126" }
fedimint-server = { git = "https://github.com/fedimint/fedimint", rev = "33f80b29ca0640ed83d66d6823aa1e12f09da126" }
fedimint-client = { git = "https://github.com/fedimint/fedimint", rev = "33f80b29ca0640ed83d66d6823aa1e12f09da126" }
fedimint-logging = { git = "https://github.com/fedimint/fedimint", rev = "33f80b29ca0640ed83d66d6823aa1e12f09da126" }
fedimint-testing = { git = "https://github.com/fedimint/fedimint", rev = "33f80b29ca0640ed83d66d6823aa1e12f09da126" }
devimint = { git = "https://github.com/fedimint/fedimint", rev = "33f80b29ca0640ed83d66d6823aa1e12f09da126" }
aead = { git = "https://github.com/fedimint/fedimint", rev = "33f80b29ca0640ed83d66d6823aa1e12f09da126" }
tbs = { git = "https://github.com/fedimint/fedimint", rev = "33f80b29ca0640ed83d66d6823aa1e12f09da126" }
threshold_crypto = { git = "https://github.com/fedimint/threshold_crypto" }

clap = { version = "4.5.4", features = ["derive", "std", "help", "usage", "error-context", "suggestions", "env"], default-features = false }
nostr-sdk = "0.30.0"

# Comment above lines and uncomment these to work with local fedimint dependencies
#fedimintd = { path = "../fedimint/fedimintd" }
#fedimint-cli = { path = "../fedimint/fedimint-cli" }
#fedimint-core = { path = "../fedimint/fedimint-core" }
#fedimint-server = { path = "../fedimint/fedimint-server" }
#fedimint-client = { path = "../fedimint/fedimint-client" }
#fedimint-logging = { path = "../fedimint/fedimint-logging" }
#fedimint-testing = { path = "../fedimint/fedimint-testing" }
#devimint = { path = "../fedimint/devimint" }
#aead = { path = "../fedimint/aead" }
#tbs = { path = "../fedimint/tbs" }

[profile.dev]
split-debuginfo = "packed"

# in dev mode optimize crates that are perf-critical (usually just crypto crates)
[profile.dev.package]
secp256k1 = { opt-level = 3 }
secp256k1-zkp = { opt-level = 3 }
secp256k1-sys = { opt-level = 3 }
secp256k1-zkp-sys = { opt-level = 3 }
bitcoin_hashes = { opt-level = 3 }
ff = { opt-level = 3 }
group = { opt-level = 3 }
pairing = { opt-level = 3 }
rand_core = { opt-level = 3 }
byteorder = { opt-level = 3 }
zeroize = { opt-level = 3 }
bls12_381 = { opt-level = 3 }
subtle = { opt-level = 3 }
ring = { opt-level = 3 }
threshold_crypto = { opt-level = 3 }
