[package]
name = "roastr-tests"
version = "0.0.1"
authors = ["m1sterc001guy"]
edition = "2021"
description = "A federated nostr client."
license = "MIT"
publish = false

[[test]]
name = "roastr_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = "1.0.66"
fedimint-client = { workspace = true }
fedimint-dummy-client = { git = "https://github.com/fedimint/fedimint", tag = "v0.3.0" }
fedimint-dummy-common = { git = "https://github.com/fedimint/fedimint", tag = "v0.3.0" }
fedimint-dummy-server = { git = "https://github.com/fedimint/fedimint", tag = "v0.3.0" }
fedimint-core = { workspace = true }
roastr-client = { path = "../roastr-client" }
roastr-common = { path = "../roastr-common" }
roastr-server = { path = "../roastr-server" }
fedimint-logging = { workspace = true }
fedimint-server = { workspace = true }
fedimint-testing = { workspace = true }
rand = "0.8"
tokio = { version = "1.26.0", features = ["sync"] }
tracing = "0.1.37"
schnorr_fun = { version = "0.10.0", features = ["serde", "bincode"] }
sha2 = "0.10"

[dev-dependencies]
threshold_crypto = { workspace = true }
